In [59]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [60]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [61]:
print(x)

[['Anggur' 30.0 45000.0]
 ['Apel' 70.0 45000.0]
 ['Semangka' 40.0 65000.0]
 ['Pisang' 50.0 60000.0]
 ['Apel' 60.0 nan]
 ['Pisang' 45.0 60000.0]
 ['Semangka' nan 55000.0]
 ['Anggur' 65.0 80000.0]
 ['Pisang' 50.0 80000.0]
 ['Apel' 45.0 70000.0]]


In [62]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [63]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [64]:
print(x)

[['Anggur' 30.0 45000.0]
 ['Apel' 70.0 45000.0]
 ['Semangka' 40.0 65000.0]
 ['Pisang' 50.0 60000.0]
 ['Apel' 60.0 62222.22222222222]
 ['Pisang' 45.0 60000.0]
 ['Semangka' 50.55555555555556 55000.0]
 ['Anggur' 65.0 80000.0]
 ['Pisang' 50.0 80000.0]
 ['Apel' 45.0 70000.0]]


In [65]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [66]:
print(x)

[[1.0 0.0 0.0 0.0 30.0 45000.0]
 [0.0 1.0 0.0 0.0 70.0 45000.0]
 [0.0 0.0 0.0 1.0 40.0 65000.0]
 [0.0 0.0 1.0 0.0 50.0 60000.0]
 [0.0 1.0 0.0 0.0 60.0 62222.22222222222]
 [0.0 0.0 1.0 0.0 45.0 60000.0]
 [0.0 0.0 0.0 1.0 50.55555555555556 55000.0]
 [1.0 0.0 0.0 0.0 65.0 80000.0]
 [0.0 0.0 1.0 0.0 50.0 80000.0]
 [0.0 1.0 0.0 0.0 45.0 70000.0]]


In [67]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [68]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [69]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [70]:
print(x_train)

[[0.0 0.0 0.0 1.0 50.55555555555556 55000.0]
 [0.0 1.0 0.0 0.0 60.0 62222.22222222222]
 [1.0 0.0 0.0 0.0 30.0 45000.0]
 [0.0 0.0 1.0 0.0 50.0 60000.0]
 [0.0 1.0 0.0 0.0 70.0 45000.0]
 [1.0 0.0 0.0 0.0 65.0 80000.0]
 [0.0 0.0 1.0 0.0 50.0 80000.0]
 [0.0 0.0 1.0 0.0 45.0 60000.0]]


In [71]:
print(x_test)

[[0.0 0.0 0.0 1.0 40.0 65000.0]
 [0.0 1.0 0.0 0.0 45.0 70000.0]]


In [72]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [73]:
print(y_test)

[0 1]


In [74]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [75]:
print(x_train)

[[0.0 0.0 0.0 2.6457513110645903 -0.17194112402745307 -0.4678599812967005]
 [0.0 1.0 0.0 -0.3779644730092272 0.6344034576185349 0.10458046640749719]
 [1.0 0.0 0.0 -0.3779644730092272 -1.926926389962839 -1.2604698319640515]
 [0.0 0.0 1.0 -0.3779644730092272 -0.21937315824192308 -0.071555055963025]
 [0.0 1.0 0.0 -0.3779644730092272 1.4881800734789927 -1.2604698319640515]
 [1.0 0.0 0.0 -0.3779644730092272 1.061291765548764 1.5136646453716769]
 [0.0 0.0 1.0 -0.3779644730092272 -0.21937315824192308 1.5136646453716769]
 [0.0 0.0 1.0 -0.3779644730092272 -0.6462614661721521 -0.071555055963025]]


In [76]:
print(x_test)

[[0.0 0.0 0.0 2.6457513110645903 -1.073149774102381 0.3247498693706505]
 [0.0 1.0 0.0 -0.3779644730092272 -0.6462614661721521 0.721054794704326]]
